### ISSUE TITLE
Wrong length of the token

### ISSUE THREAD

**Issue by hamiddhosseini** [EnAccess/OpenPAYGO#12]
Hello there, 
I'm Seyedhamid hosseini from Qotto and I'm starting this issue to discuss a problem we encounter from time to time. 
We're using the following parameters to generate an activation token: 
 - a key
 - a counter
 - a starting code
 - the duration

As it is mentioned in the documentation, the activation token is supposed to contain 9 digits, however, from time to time and for specific combinations of the above-mentioned parameters; an 8 digits token is generated.
That being said, this wrong format of the token causes the process to fail and the client has to start again.

**Comment by benmod** [comment]
Hi! 

In this type of cases you just need to pad the token with leading 0s and it should work as expected. 

You can use the following example code to convert your token integer into a properly padded string: 

`'{:09d}'.format(token)`

**Comment by hamiddhosseini** [comment]
Thanks a lot for your response, we implemented the suggested method and tested it recently.
The issue seems to be fixed for us.

**Comment by PandA88pl** [comment]
@

> Hello there, I'm Seyedhamid hosseini from Qotto and I'm starting this issue to discuss a problem we encounter from time to time. We're using the following parameters to generate an activation token:
> 
> * a key
> * a counter
> * a starting code
> * the duration
> 
> As it is mentioned in the documentation, the activation token is supposed to contain 9 digits, however, from time to time and for specific combinations of the above-mentioned parameters; an 8 digits token is generated. That being said, this wrong format of the token causes the process to fail and the client has to start again.
