### ISSUE TITLE
Request for improvement : Packaging OpenPAYGO

### ISSUE THREAD

**Issue by PhilippeGalvan** [EnAccess/OpenPAYGO#8]
Hello! First of all, thanks for your work on OpenPAYGO!

I'm creating this issue because I need to wrap OpenPAYGO in an app for a client and I would like to integrate it as a dependency instead of copied files.

It could be useful for other users as well imo !

Sincerely,
Philippe

**Comment by benmod** [comment]
Hello!

Do you mean you would like it as a Python package? Or for which language
would you want a dependency?

Cheers!
Ben

Le jeu. 3 sept. 2020 à 16:09, PhilippeGalvan <notifications@github.com> a
écrit :

**Comment by PhilippeGalvan** [comment]
Thank you for your reactivity, It would be as a python (pip) package :)

**Comment by syenchuk** [comment]
Hi Ben, do you think you will be able to package this library soon?

**Comment by aartimahajan444** [comment]
> Hello! First of all, thanks for your work on OpenPAYGO!
> 
> I'm creating this issue because I need to wrap OpenPAYGO in an app for a client and I would like to integrate it as a dependency instead of copied files.
> 
> It could be useful for other users as well imo !
> 
> Sincerely,
> Philippe

Hi Philippe,

Is it possible for us to connect over the email to learn more about the app and its usage where you would be incorporating OpenPayGo? This is to facilitate our effort in promoting the open source technologies and its impact across the wider sector. We can connect via private message.   Appreciate your support on this. Thanks. Aarti

**Comment by syenchuk** [comment]
@benmod @aartimahajan444 depending on your response, we can also offer you to package this module by ourselves and submit it to pypi. We could then share ownership with your pypi account.

**Comment by benmod** [comment]
Hi Alex,

We are planning on publishing to pypy in the next 2 weeks, together with
some additional features.

Cheers!
Ben

**Comment by syenchuk** [comment]
Thanks Ben, we'll wait for this then.

**Comment by aartimahajan444** [comment]
> Thanks Ben, we'll wait for this then.



> @benmod @aartimahajan444 depending on your response, we can also offer you to package this module by ourselves and submit it to pypi. We could then share ownership with your pypi account.

Hi Alex, Let me know way to connect with you directly to learn more about how your organisation and incorporation of OpenPAYGO technology. thanks. Aarti

**Comment by PhilippeGalvan** [comment]
@aartimahajan444 

> Hi Philippe,
>
>Is it possible for us to connect over the email to learn more about the app and its usage where you would be incorporating >OpenPayGo? This is to facilitate our effort in promoting the open source technologies and its impact across the wider >sector. We can connect via private message. Appreciate your support on this. Thanks. Aarti

Alexpirine is the best person to talk about qotto and OpenPAYGO usecase !

**Comment by syenchuk** [comment]
> Hi Alex, Let me know way to connect with you directly to learn more about how your organisation and incorporation of OpenPAYGO technology. thanks. Aarti

@aartimahajan444 we can get in touch by email (sacha at qotto dot net)

**Comment by aartimahajan444** [comment]
@alexpirine Thanks sent an email to you. Let me know if you got it.

**Comment by wan5xp** [comment]
I have made a pull request #10 regarding this topic. I am also still new in python, but I hope this can help you in packaging this

**Comment by mujeeb-bboxx** [comment]
>We are planning on publishing to pypi in the next 2 weeks

@benmod has the pypi package been released? If not, can you please tell when is it expected to get released?

**Comment by benmod** [comment]
The package is now available on pip: https://pypi.org/project/openpaygo-token
